[package]
name = "d-dash"
version = "0.1.0"
edition = "2024"
authors = ["Burak Selim Senyurt"]
description = "A simple disk usage analyzer written in Rust."
license = "MIT"
repository = "https://github.com/buraksenyurt/tools"

[dependencies]
colorized = "1.0.0"
