[package]
name = "port-scan"
version = "0.1.0"
edition = "2021"
authors = ["Burak Selim Senyurt"]
description = "A simple port scanner written in Rust."
license = "MIT"
repository = "https://github.com/buraksenyurt/tools"

[dependencies]
colorized = "1.0.0"
